version: '3.9'

services:
  app:
    build: ../server
    volumes:
      - ../server:/app
    ports:
      - "5000:5000"

  proxy:
    build: ../proxy
    ports:
      - "80:80"

  mongo:
    volumes:
      - ../database/:/data/db:rw

  mongo-express:
    ports:
      - "8081:8081"