version: '3.9'

services:
  app:
    container_name: app
    restart: always
    environment:
      MONGO_URL: mongodb://mongo:27017/${MONGO_DATABASE:-test}
      REFRESH_TOKEN: ${REFRESH_TOKEN:-my-secret-refresh-token}
      ACCESS_TOKEN: ${ACCESS_TOKEN:-my-secret-access-token}
      WAIT_HOSTS: mongo:27017
    depends_on:
      - mongo

  proxy:
    container_name: proxy
    restart: always
    depends_on:
      - app

  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.4.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-username}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:-username}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:-password}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - mongo
